[package]
name = "sc-state-db"
version = "0.10.0-dev"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axlib/"
description = "State database maintenance. Handles canonicalization and pruning in the database."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parking_lot = "0.11.1"
log = "0.4.11"
sc-client-api = { version = "4.0.0-dev", path = "../api" }
sp-core = { version = "4.0.0-dev", path = "../../primitives/core" }
codec = { package = "axc-scale-codec", version = "2.0.0", features = ["derive"] }
axc-util-mem = { version = "0.10.0", default-features = false, features = ["primitive-types"] }
axc-util-mem-derive = "0.1.0"
