[package]
name = "sp-test-primitives"
version = "2.0.0"
authors = ["AXIA Technologies <admin@axiacoin.network>"]
edition = "2018"
license = "Apache-2.0"
homepage = ""
repository = "https://github.com/axia-tech/axlib/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-application-crypto = { version = "4.0.0-dev", default-features = false, path = "../application-crypto" }
codec = { package = "axc-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-core = { version = "4.0.0-dev", default-features = false, path = "../core" }
serde = { version = "1.0.126", optional = true, features = ["derive"] }
sp-runtime = { version = "4.0.0-dev", default-features = false, path = "../runtime" }
axc-util-mem = { version = "0.10.0", default-features = false, features = ["primitive-types"] }

[features]
default = [
	"std",
]
std = [
	"sp-application-crypto/std",
	"serde",
]
